[workspace]
authors = ["Byron"]
channels = ["conda-forge"]
name = "stem-foss"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]
init-db = "(cd ./postgresql/base) || mkdir -p ./postgresql && initdb -D ./postgresql"
check-db-server = "psql -U postgres -d stem_db -c 'CREATE TABLE Test (id INT PRIMARY KEY);DROP TABLE Test' > /dev/null"
start-db-server = "(pixi run check-db-server) || pg_ctl start -D ./postgresql -o '-h localhost -p 5432' -l ./postgresql/logfile"
stop-db-server = "(pixi run check-db-server) || pg_ctl stop -D ./postgresql"
create-db = { cmd = "createuser postgres && createdb --owner postgres stem_db", depends-on = [
    "init-db",
    "start-db-server",
] }
update-nodejs = "npm install --save-dev"
compile-ts = "tsc"
watch-ts = "tsc -w"
build = "npm run build"
pre-commit = "npx lint-staged && ruff check --fix && ruff format"
frontend = { cmd = "(pixi run watch-ts &) ; npm run dev", depends-on = [
    "update-nodejs",
    "compile-ts",
] }
backend-tests = "pytest --cov=app backend/tests/"

[dependencies]
python = ">=3.11"
fastapi = ">=0.135.1,<0.136"
pyyaml = ">=6.0.3,<7"
nodejs = "24.14.*"
numpy = ">=2.4.2,<3"
python-dotenv = ">=1.2.2,<2"
sqlmodel = ">=0.0.37,<0.0.38"
psycopg = ">=3.3.3,<4"
postgresql = "*"
ruff = "*"
pre-commit = "*"
uvicorn = "*"
polars = ">=1.38.1,<2"
npx = ">=0.1.1,<0.2"

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"

[feature.py314.dependencies]
python = "3.14.*"

[feature.test.dependencies]
sqlite = "*"
pytest = "*"
pytest-cov = "*"

[tool.ruff]
line-length = 88

[tool.ruff.format]
docstring-code-format = true

[environments]
default = ["py314"]
test-py311 = ["py311", "test"]
test-py312 = ["py312", "test"]
test-py313 = ["py313", "test"]
test-py314 = ["py314", "test"]

[tasks.test-all]
depends-on = [
    { task = "backend-tests", environment = "test-py311" },
    { task = "backend-tests", environment = "test-py312" },
    { task = "backend-tests", environment = "test-py313" },
    { task = "backend-tests", environment = "test-py314" },
]
